# LoggedFS-python
# Filesystem monitoring with Fuse and Python
# https://github.com/pleiszenburg/loggedfs-python
#
#	.travis.yml: Configuration for Travis CI build test
#
# 	Copyright (C) 2017-2018 Sebastian M. Ernst <ernst@pleiszenburg.de>
#
# <LICENSE_BLOCK>
# The contents of this file are subject to the Apache License
# Version 2 ("License"). You may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# https://www.apache.org/licenses/LICENSE-2.0
# https://github.com/pleiszenburg/loggedfs-python/blob/master/LICENSE
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the
# specific language governing rights and limitations under the License.
# </LICENSE_BLOCK>


# Check this file at:
# http://lint.travis-ci.org/

# A virtual machine IS required for loading FUSE kernel module:
# https://github.com/travis-ci/travis-ci/issues/1100#issuecomment-160169121
sudo: required

# Repository language
language: python

# Ubuntu & Python versions
matrix:
    include:
        - dist: xenial
          python: "3.5"
        - dist: xenial
          python: "3.6"
        - dist: xenial
          python: "3.7"
        - dist: xenial
          python: "3.8"
        - dist: bionic
          python: "3.5"
        - dist: bionic
          python: "3.6"
        - dist: bionic
          python: "3.7"
        - dist: bionic
          python: "3.8"
# Install dependencies
addons:
  apt:
    packages:
    - fuse
    - libfuse2
    - libfuse-dev

# Get debug output
before_install:
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
  - sudo echo "user_allow_other" | sudo tee -a /etc/fuse.conf > /dev/null
  - python --version
  - pip install -U pip
  - pip install -U setuptools
  - uname -a

# command to install dependencies and module
#install: make install

# command to run tests
script: python3 main.py

# Notify developers
notifications:
  email:
    recipients:
      - wwin3286tw@gmail.com
    on_success: always
    on_failure: always
